=== mintbox/WBA2_SS13_Oli/WBA2_Phase1/src/Aufgabe_3d_V2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xs:schema PUBLIC "-//W3C//DTD XMLSCHEMA 200102//EN" "http://www.w3.org/2001/XMLSchema.dtd">
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/Aufgabe_3d"
           elementFormDefault="qualified">
    <xs:element name="Rezepte">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Rezept" maxOccurs="unbounded" minOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Titel" type="xs:string" maxOccurs="1" minOccurs="1"/>
                            <xs:element name="Autor" type="xs:string" />
                            <xs:element name="Datum" type="xs:date" />
                            <xs:element name="Bild" type="xs:anyURI" maxOccurs="1" minOccurs="0"/>
                            <xs:element name="Zutaten" maxOccurs="1" minOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Zutat" maxOccurs="unbounded" minOccurs="1">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Name" type="xs:string" maxOccurs="1"
                                                                minOccurs="1"/>
                                                    <xs:element name="Menge" type="xs:float" maxOccurs="1"
                                                                minOccurs="0"/>
                                                </xs:sequence>
                                                <xs:attribute name="Einheit" default="g">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:string">
                                                            <xs:enumeration value="g"/>
                                                            <xs:enumeration value="Pck."/>
                                                            <xs:enumeration value="EL"/>
                                                            <xs:enumeration value="ml"/>
                                                            <xs:enumeration value="Prise"/>
                                                            <xs:enumeration value="Dose"/>
                                                            <xs:enumeration value="TL"/>
                                                            <xs:enumeration value="Pkt."/>
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Zubereitung" maxOccurs="1" minOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Arbeitszeit">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Dauer" type="xs:integer"/>
                                                </xs:sequence>
                                                <xs:attribute name="Einheit">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:string">
                                                            <xs:enumeration value="std"/>
                                                            <xs:enumeration value="min"/>
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="Schwierigkeitsgrad">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="simpel"/>
                                                    <xs:enumeration value="normal"/>
                                                    <xs:enumeration value="pfiffig"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="Brennwert" maxOccurs="1" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Anzahl" type="xs:integer"/>
                                                </xs:sequence>
                                                <xs:attribute name="Einheit">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:string">
                                                            <xs:enumeration value="kcal"/>
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="Arbeitsschritte" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Kommentare" maxOccurs="1" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Kommentar" type="xs:string" maxOccurs="unbounded"
                                                    minOccurs="0"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== mintbox/WBA2_SS13_Oli/WBA2_Phase1/bin/Aufgabe_3d_V2.xml
<?xml version="1.0" encoding="UTF-8"?>
<Rezepte xmlns="http://www.example.org/Aufgabe_3d" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.example.org/Aufgabe_3d Aufgabe_3d_V2.xsd ">
    <Rezept>
        <Titel>Goldener Toast</Titel>
        <Autor>Lubu</Autor>
        <Datum>2007-05-06</Datum>
        <Zutaten>
            <Zutat Einheit="g">
                <Name>Salz</Name>
                <Menge>18</Menge>
            </Zutat>
            <Zutat Einheit="ml">
                <Name>Wasser</Name>
                <Menge>100</Menge>
            </Zutat>
            <Zutat Einheit="g">
                <Name>Hefe</Name>
                <Menge>12</Menge>
            </Zutat>
            <Zutat Einheit="g">
                <Name>Mehl</Name>
                <Menge>1000</Menge>
            </Zutat>
            <Zutat Einheit="g">
                <Name>Zucker</Name>
                <Menge>20</Menge>
            </Zutat>
            <Zutat Einheit="g">
                <Name>Stärkemehl</Name>
                <Menge>20</Menge>
            </Zutat>
            <Zutat Einheit="g">
                <Name>Butter</Name>
                <Menge>60</Menge>
            </Zutat>
            <Zutat Einheit="g">
                <Name>Malz</Name>
                <Menge>20</Menge>
            </Zutat>
            <Zutat Einheit="ml">
                <Name>Milch</Name>
                <Menge>500</Menge>
            </Zutat>
        </Zutaten>
        <Zubereitung>
            <Arbeitszeit>
                <Dauer>15</Dauer>
            </Arbeitszeit>
            <Schwierigkeitsgrad>normal</Schwierigkeitsgrad>

            <Arbeitsschritte>Zuerst das Salz mit dem Wasser und der Hefe gut verrühren und mindestens 30 Minuten, auch
                länger, bis zu 20 Stunden(!) stehen lassen.

                Danach die restlichen Zutaten (Butter zuletzt) und den Hefeansatz gut 10 Minuten maschinell zu einem
                mittelfesten Teig verkneten. Der Teig klebt leicht, das gibt sich aber, nicht mehr Mehl daran geben!

                Dann gut mit Plastik abdecken und doppelt aufgehen lassen, das kann 2-3 Stunden dauern. Danach auf
                leicht bemehlter Arbeitsfläche kurz zusammenwirken und in eine sehr große Kastenform füllen, maximal bis
                zur halben Höhe, oder auf drei kleinere Formen aufteilen. Der Teig geht sehr stark auf, trotz dem
                geringen Hefeanteil.

                Das Backrohr auf 200°C vorheizen. Die Backform mit einem Tuch abdecken und den Teig gut 1/3 aufgehen
                lassen, dann ins Backrohr geben. Ich gieße dann sofort 1 Tasse Wasser ins Rohr.

                Die Backzeit ist bei mir 35-40 Minuten Heißluft, bei leicht abfallender Hitze bis 175°C.
            </Arbeitsschritte>
        </Zubereitung>
        <Kommentare>
            <Kommentar Autor="bibi14" Datum="2008-01-26" Uhrzeit="11:25:00" Text="Hallo Burgi,
                dein Toast Brot hab ich schon zweimal gebacken , schnell und einfach super.
                Überhaupt deine ganzen Rezepte, Kompliment.
                Mach weiter so.

                Liebe grüße
                Gaby(bibi14)" />
            <Kommentar Autor="Lubu" Datum="2008-01-26" Uhrzeit="12:27:00" Text="Liebe Gaby,
                mich freuts, dass er gelungen und auch gut schmeckt; ich backe auch nur mehr nach diesem Rezept.
                Danke!

                LG Burgi" />
        </Kommentare>
    </Rezept>
    <Rezept>
    <Titel></Titel>
    	<Autor></Autor>
    	<Datum></Datum>
    	<Zutaten>
    	<Zutat>
    	<Name></Name>
    	<Menge></Menge>
    	</Zutat>
    	</Zutaten>
    	
    </Rezept>
</Rezepte>
